# Generated by Django 6.1.1 on 2026-10-11 01:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EntrepriseApp', '0002_alter_utilisateur_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=20, unique=True)),
                ('ville_depart', models.CharField(max_length=100)),
                ('ville_arrivee', models.CharField(max_length=100)),
                ('poids_kg', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('date_souhaitee', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('publiee', 'Publiée'), ('attribuee', 'Attribuée'), ('en_cours', 'En cours'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='publiee', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entreprise', models.ForeignKey(limit_choices_to={'type_entreprise': 'chargeur'}, on_delete=django.db.models.deletion.CASCADE, related_name='expeditions', to='EntrepriseApp.entreprise')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
