# Generated by Django 6.1.1 on 2026-10-11 01:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EntrepriseApp', '0002_alter_utilisateur_managers_and_more'),
        ('ExpeditionApp', '0001_initial'),
        ('VehiculeApp', '0003_rename_disponibilite_vehicule_disponible_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('delai_jours', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('statut', models.CharField(choices=[('proposee', 'Proposée'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('retiree', 'Retirée')], default='proposee', max_length=20)),
                ('date_proposition', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expedition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='ExpeditionApp.expedition')),
                ('transporteur', models.ForeignKey(limit_choices_to={'type_entreprise': 'transporteur'}, on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='EntrepriseApp.entreprise')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='VehiculeApp.vehicule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
