# Generated by Django 6.1.1 on 2026-10-11 01:25

import EntrepriseApp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntrepriseApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='utilisateur',
            managers=[
                ('objects', EntrepriseApp.models.CustomUserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='entreprise',
            old_name='gerant',
            new_name='utilisateur',
        ),
        migrations.RemoveField(
            model_name='entreprise',
            name='matricule_fiscale',
        ),
        migrations.AddField(
            model_name='entreprise',
            name='matricule_fiscal',
            field=models.CharField(default='', max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='Format fiscal incorrect.', regex='^\\d{7}[/ -]?[A-Za-z][/ -]?[ABDNPEabdnpe][/ -]?[MPCNEmpcne][/ -]?\\d{3}$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='type_entreprise',
            field=models.CharField(choices=[('chargeur', 'Chargeur'), ('transporteur', 'Transporteur')], default='chargeur', max_length=100),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('chargeur', 'Chargeur'), ('transporteur', 'Transporteur')], max_length=20),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='user_id',
            field=models.CharField(default=EntrepriseApp.models.generate_user_id, editable=False, max_length=8, primary_key=True, serialize=False),
        ),
    ]
