# Generated by Django 6.1.1 on 2026-09-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehiculeApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicule',
            old_name='disponible',
            new_name='disponibilite',
        ),
        migrations.RenameField(
            model_name='vehicule',
            old_name='entreprise',
            new_name='proprietaire',
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='capacite_kg',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='immatriculation',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='type_vehicule',
            field=models.CharField(choices=[('camionnette', 'Camionnette'), ('fourgon', 'Fourgon'), ('camion porteur', 'Camion porteur'), ('semi remorque', 'Semi remorque')], default='camionnette', max_length=50),
        ),
    ]
