# Generated by Django 6.1.1 on 2026-10-11 01:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntrepriseApp', '0002_alter_utilisateur_managers_and_more'),
        ('VehiculeApp', '0002_rename_disponible_vehicule_disponibilite_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicule',
            old_name='disponibilite',
            new_name='disponible',
        ),
        migrations.RemoveField(
            model_name='vehicule',
            name='proprietaire',
        ),
        migrations.AddField(
            model_name='vehicule',
            name='entreprise',
            field=models.ForeignKey(default=1, limit_choices_to={'type_entreprise': 'transporteur'}, on_delete=django.db.models.deletion.CASCADE, related_name='vehicules', to='EntrepriseApp.entreprise'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='capacite_kg',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(100, 'Capacité doit être supérieure à 100 kg.')]),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='immatriculation',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='type_vehicule',
            field=models.CharField(choices=[('camionnette', 'Camionnette'), ('fourgon', 'Fourgon'), ('camion porteur', 'Camion porteur'), ('semi-remorque', 'Semi-remorque')], default='camionnette', max_length=50),
        ),
    ]
